import { useState, useEffect } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { managerService, Manager, ManagerPermissions, CreateManagerData } from "@/services/manager.service";
import { useToast } from "@/hooks/use-toast";
import { useAuthStore } from "@/store/authStore";
import { LoadingOverlay } from "@/components/ui/loading-overlay";
import { getErrorMessage } from "@/lib/errorUtils";
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { ScrollArea } from "@/components/ui/scroll-area";

interface ManagerDialogProps {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    manager?: Manager | null;
}

const PERMISSION_LABELS = {
    can_manage_products: "Products",
    can_manage_categories: "Categories",
    can_manage_orders: "Orders",
    can_manage_events: "Events",
    can_manage_blogs: "Blogs",
    can_manage_testimonials: "Testimonials",
    can_manage_gallery: "Gallery",
    can_manage_faqs: "FAQs",
    can_manage_carousel: "Carousel Slides",
    can_manage_contact_info: "Contact Information",
    can_manage_social_media: "Social Media",
    can_manage_bank_details: "Bank Details",
    can_manage_about_us: "About Us",
    can_manage_newsletter: "Newsletter",
};

export function ManagerDialog({ open, onOpenChange, manager }: ManagerDialogProps) {
    const [email, setEmail] = useState("");
    const [name, setName] = useState("");
    // Password is auto-generated by backend
    const [permissions, setPermissions] = useState<Record<string, boolean>>({});
    const [selectAll, setSelectAll] = useState(false);

    const { toast } = useToast();
    const queryClient = useQueryClient();
    const { user } = useAuthStore();

    // Reset form when dialog opens/closes or manager changes
    useEffect(() => {
        if (open) {
            if (manager) {
                setEmail(manager.email);
                setName(manager.name);

                // Set permissions
                // Set permissions
                const permissionsData = Array.isArray(manager.manager_permissions)
                    ? manager.manager_permissions[0]
                    : manager.manager_permissions;

                if (permissionsData) {
                    const newPerms: Record<string, boolean> = {};
                    Object.entries(permissionsData).forEach(([key, value]) => {
                        if (key.startsWith("can_manage_") && typeof value === "boolean") {
                            newPerms[key] = value;
                        }
                    });
                    setPermissions(newPerms);
                    setSelectAll(Object.values(newPerms).every((v) => v));
                } else {
                    setPermissions({});
                    setSelectAll(false);
                }
            } else {
                // Reset for new manager
                setEmail("");
                setName("");
                setPermissions({});
                setSelectAll(false);
            }
        }
    }, [manager, open]);

    const createMutation = useMutation({
        mutationFn: (data: CreateManagerData) => managerService.create({
            ...data,
            created_by: user?.id
        }),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ["managers"] });
            toast({ title: "Manager created successfully" });
            onOpenChange(false);
            // form.reset(); // This line was in the instruction but 'form' object is not defined in the current context.
            // Keeping it commented out to avoid compilation errors, as the component uses useState for form fields.
            // If a form library like react-hook-form is introduced, this line would be relevant.
        },
        onError: (error: unknown) => {
            toast({
                title: "Failed to create manager",
                description: getErrorMessage(error, "Failed to create manager"),
                variant: "destructive",
            });
        },
    });

    const updateMutation = useMutation({
        mutationFn: (data: { id: string; permissions: Record<string, boolean> }) =>
            managerService.updatePermissions(data.id, data.permissions),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ["managers"] });
            toast({ title: "Manager permissions updated successfully" });
            onOpenChange(false);
        },
        onError: (error: unknown) => {
            toast({
                title: "Failed to update manager",
                description: getErrorMessage(error, "Failed to update manager"),
                variant: "destructive",
            });
        },
    });

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();

        if (!email.trim() || !name.trim()) {
            toast({
                title: "Error",
                description: "Email and name are required",
                variant: "destructive",
            });
            return;
        }



        if (manager) {
            updateMutation.mutate({
                id: manager.id,
                permissions,
            });
        } else {
            createMutation.mutate({
                email: email.trim(),
                name: name.trim(),
                permissions,
            });
        }
    };

    const handleSelectAll = (checked: boolean) => {
        setSelectAll(checked);
        const newPerms: Record<string, boolean> = {};
        Object.keys(PERMISSION_LABELS).forEach((key) => {
            newPerms[key] = checked;
        });
        setPermissions(newPerms);
    };

    const handlePermissionChange = (key: string, checked: boolean) => {
        const newPerms = { ...permissions, [key]: checked };
        setPermissions(newPerms);
        setSelectAll(Object.values(newPerms).every((v) => v));
    };

    return (
        <Dialog open={open} onOpenChange={onOpenChange}>
            <DialogContent className="sm:max-w-3xl max-h-[90vh] flex flex-col">
                <LoadingOverlay isLoading={createMutation.isPending || updateMutation.isPending} />
                <DialogHeader className="flex-shrink-0">
                    <DialogTitle>{manager ? "Edit Manager Permissions" : "Create New Manager"}</DialogTitle>
                    <DialogDescription>
                        {manager
                            ? "Update the manager's access permissions"
                            : "Create a new manager account with specific permissions"}
                    </DialogDescription>
                </DialogHeader>

                <form onSubmit={handleSubmit} className="flex flex-col flex-1 min-h-0">
                    <ScrollArea className="flex-1 p-1">
                        <div className="space-y-4 py-2 px-2">
                            {/* Basic Info */}
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div className="space-y-2">
                                    <Label htmlFor="email" className="text-sm">
                                        Email <span className="text-destructive">*</span>
                                    </Label>
                                    <Input
                                        id="email"
                                        type="email"
                                        value={email}
                                        onChange={(e) => setEmail(e.target.value)}
                                        placeholder="manager@example.com"
                                        disabled={!!manager}
                                        required
                                        autoComplete="off"
                                        className="h-9 w-full border border-input disabled:opacity-100 disabled:bg-muted/50"
                                    />
                                </div>

                                <div className="space-y-2">
                                    <Label htmlFor="name" className="text-sm">
                                        Name <span className="text-destructive">*</span>
                                    </Label>
                                    <Input
                                        id="name"
                                        type="text"
                                        value={name}
                                        onChange={(e) => setName(e.target.value)}
                                        placeholder="John Doe"
                                        disabled={!!manager}
                                        required
                                        autoComplete="off"
                                        className="h-9 w-full border border-input disabled:opacity-100 disabled:bg-muted/50"
                                    />
                                </div>

                                <p className="text-xs text-muted-foreground md:col-span-2">
                                    Note: A temporary password will be auto-generated and emailed to the manager.
                                </p>
                            </div>

                            {/* Permissions */}
                            <div className="space-y-3 pt-2 border-t">
                                <div className="flex items-center justify-between">
                                    <Label className="text-sm font-semibold">Module Permissions</Label>
                                    <div className="flex items-center space-x-2">
                                        <Checkbox
                                            id="select-all"
                                            checked={selectAll}
                                            onCheckedChange={handleSelectAll}
                                        />
                                        <label
                                            htmlFor="select-all"
                                            className="text-xs font-medium leading-none cursor-pointer"
                                        >
                                            Select All
                                        </label>
                                    </div>
                                </div>

                                <div className="grid grid-cols-2 md:grid-cols-3 gap-x-6 gap-y-2.5">
                                    {Object.entries(PERMISSION_LABELS).map(([key, label]) => (
                                        <div key={key} className="flex items-center space-x-2">
                                            <Checkbox
                                                id={key}
                                                checked={permissions[key] || false}
                                                onCheckedChange={(checked) =>
                                                    handlePermissionChange(key, checked as boolean)
                                                }
                                            />
                                            <label
                                                htmlFor={key}
                                                className="text-xs font-medium leading-none cursor-pointer"
                                            >
                                                {label}
                                            </label>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>
                    </ScrollArea>

                    <DialogFooter className="flex-shrink-0 mt-4 pt-4 border-t">
                        <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
                            Cancel
                        </Button>
                        <Button
                            type="submit"
                            disabled={createMutation.isPending || updateMutation.isPending}
                        >
                            {manager ? "Update Permissions" : "Create Manager"}
                        </Button>
                    </DialogFooter>
                </form>
            </DialogContent>
        </Dialog >
    );
}
