/**
 * Email Event Types
 * Centralized enum for all email events in the application
 */
const EmailEventTypes = {
    // User Authentication
    USER_REGISTRATION: 'USER_REGISTRATION',
    EMAIL_CONFIRMATION: 'EMAIL_CONFIRMATION',
    PASSWORD_CHANGED: 'PASSWORD_CHANGED',
    PASSWORD_RESET: 'PASSWORD_RESET',

    // Orders
    ORDER_PLACED: 'ORDER_CONFIRMATION',
    ORDER_STATUS_UPDATE: 'ORDER_STATUS_UPDATE',
    ORDER_SHIPPED: 'ORDER_SHIPPED',
    ORDER_DELIVERED: 'ORDER_DELIVERED',

    // Payment & Invoice
    PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
    GST_INVOICE_GENERATED: 'GST_INVOICE_GENERATED',

    // Returns
    RETURN_REQUESTED: 'RETURN_REQUESTED',
    RETURN_APPROVED: 'RETURN_APPROVED',
    RETURN_REJECTED: 'RETURN_REJECTED',

    // Refunds
    REFUND_INITIATED: 'REFUND_INITIATED',
    REFUND_COMPLETED: 'REFUND_COMPLETED',

    // Events
    EVENT_REGISTRATION: 'EVENT_REGISTRATION',
    EVENT_CANCELLATION: 'EVENT_CANCELLATION',
    EVENT_UPDATE: 'EVENT_UPDATE',

    // Donations
    DONATION_RECEIPT: 'DONATION_RECEIPT',

    // Subscriptions
    SUBSCRIPTION_STARTED: 'SUBSCRIPTION_STARTED',
    SUBSCRIPTION_CANCELLED: 'SUBSCRIPTION_CANCELLED',
    SUBSCRIPTION_RENEWED: 'SUBSCRIPTION_RENEWED',

    // Contact
    CONTACT_FORM: 'CONTACT_FORM',

    // Account Management
    ACCOUNT_DELETED: 'ACCOUNT_DELETED',
    ACCOUNT_DELETION_SCHEDULED: 'ACCOUNT_DELETION_SCHEDULED',
    ACCOUNT_DELETION_OTP: 'ACCOUNT_DELETION_OTP',
    MANAGER_WELCOME: 'MANAGER_WELCOME',

    // OTP (legacy support)
    OTP_VERIFICATION: 'OTP_VERIFICATION'
};

module.exports = { EmailEventTypes };
